services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - chatbot-net

  chatbot:
    container_name: chatbot
    build:
      context: .
      dockerfile: ./apps/chatbot/Dockerfile
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - chatbot-net
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq

  event-worker:
    container_name: event-worker
    build:
      context: .
      dockerfile: ./apps/event-worker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - chatbot-net
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq

  message-worker:
    container_name: message-worker
    build:
      context: .
      dockerfile: ./apps/message-worker/Dockerfile
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - chatbot-net
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq

networks:
  chatbot-net:
    driver: bridge