###

POST http://localhost:3001/
Content-Type: application/json

{
    "event": "appointment-created",
    "appointmentId": "4"
}

###

POST http://localhost:3001/
Content-Type: application/json

{
    "event": "confirm-appointment",
    "appointmentId": "4"
}

###