@token = seu_token

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "userId": "teste",
    "name": "teste"
} 

###

POST http://localhost:3000/events/emit
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "event": "appointment-created",
    "appointmentId": "2"
}

###

POST http://localhost:3000/events/emit
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "event": "confirm-appointment",
    "appointmentId": "2"
}

###

###

POST http://localhost:3000/events/emit
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "event": "collect-feedback",
    "appointmentId": "2"
}

###